Public Class frmMain
    Public Sub frmMain_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        'Items Added to the list for the Combobox
        Dim list As New List(Of String)
        Dim userValue As String = Console.ReadLine()

        list.Add("Television")
        list.Add("Microwave")
        list.Add("Space Heater")
        list.Add("Dishwasher")
        list.Add("Coffee Maker")
        list.Add("Hair Dryer")
        list.Add("Game Console")
        list.Add("Gamma Blast")
        list.Add("Washing Machine")
        list.Add("Refrigerator")
        list.Add("Sewing Machine")
        list.Add("Vacuum")
        list.Add("Ice Maker")
        list.Add("Humidifiers")
        list.Add("Water Heater")
        list.Add("Trash Compactor")
        list.Add("Lamp")
        list.Add("Stereo")
        list.Add("Internet Router")
        list.Add("Stove")
        list.Add("Oven")
        list.Add("Electric Hot Plate")
        list.Add("Blender")
        list.Add("Electric Mixer")
        list.Add("Slow Cooker")
        list.Add("Electric Pressure Cooker")
        list.Add("Heater")
        list.Add("Dishwasher")
        list.Add("Drink Machine")
        list.Add("Brewer System")
        list.Add("tablet")
        list.Add("cellphone")
        list.Add("Camcorder")
        list.Add("Power Wheel 6v")
        list.Add("Power Wheel 12v")
        list.Add("Electrical Fireplace")
        list.Add("Deep Freezer")
        list.Add("Can Operner")
        list.Add("Hot Tub")
        list.Add("Recliner Chair")
        list.Add("Printer")
        list.Add("Fax Machine")
        list.Add("Scanner")
        list.Add("Clothes Press")
        list.Add("Clothes Iron")
        list.Add("Flat Irons")
        list.Add("Curlers")
        list.Add("Flat Iron Hot Plate")
        list.Add("Lights")
        list.Add("Fan")
        list.Add("Portable AC")
        list.Add("Window AC")
        list.Add("Electric Blanket")
        list.Add("Electric Bed")
        list.Add("Drill Gun")
        list.Add("Carpet Cleaner")
        list.Add("Alarm Clock")
        list.Add("Electric Guitar")
        list.Add("Hand Held Device")
        list.Add("DVD Player")



        Console.ReadLine()


        ' Add any initialization after the InitializeComponent() call.

    End Sub
End Class
